const Images = [
	require("../../../ui/assets/photos/sneakerball/Sneaker_ball_mar2025.mp4")
		.default,
	require("../../../ui/assets/photos/sneakerball/sb1.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb2.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb3.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb4.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb5.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb6.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb7.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb8.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb9.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb10.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb12.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb13.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb14.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb15.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb16.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb17.jpeg").default,
	require("../../../ui/assets/photos/sneakerball/sb18.jpeg").default,
	require("../../../ui/assets/photos/mentorDinner/md1.jpg").default,
	require("../../../ui/assets/photos/mentorDinner/md2.jpg").default,
	require("../../../ui/assets/photos/mentorDinner/md3.jpg").default,
	require("../../../ui/assets/photos/mentorDinner/md4.jpg").default,
	require("../../../ui/assets/photos/thanksgiving2024/tg1.jpg").default,
	require("../../../ui/assets/photos/thanksgiving2024/tg2.jpg").default,
	require("../../../ui/assets/photos/thanksgiving2024/tg3.jpg").default,
	require("../../../ui/assets/photos/thanksgiving2024/tg4.jpg").default,
	require("../../../ui/assets/photos/thanksgiving2024/tg5.jpg").default,
];

export default Images;
